# Numpy基础杂记

> 本文并不会详细记录其条目，只会记录一些需要用到的代码以及平时使用numpy时候的一些例子等等

## 一、Numpy概述
> numpy（Numerical Python）提供了python对多维数组对象的支持：ndarray，具有矢量运算能力，快速、节省空间。numpy支持高级大量的维度数组与矩阵运算，此外也针对数组运算提供大量的数学函数库。

## 二、创建ndarray数组
ndarray:Nw维数组对象，所有元素必须是相同类型
具有的属性：
1. ndim属性，表示维度个数
2. shape 属性,表示各个维度大小
3. dtype属性，表示数据类型。

In [2]:
import numpy as np # 一般是表示np

print('使用列表生成一维数组')
data = [1,2,3,4,5,6]
x = np.array(data)
print(x) #打印数组
print(x.dtype) #打印数组元素的类型

print('使用列表生成二维数组')
data = [[1,2],[3,4],[5,6]]
x = np.array(data)
print(x) #打印数组
print(x.ndim) #打印数组的维度
print(x.shape) #打印数组各个维度的长度。shape是一个元组

print('使用zero/ones/empty创建数组:根据shape来创建')
x = np.zeros(6) #创建一维长度为6的，元素都是0一维数组
print(x)
x = np.zeros((2,3)) #创建一维长度为2，二维长度为3的二维0数组
print(x)
x = np.ones((2,3)) #创建一维长度为2，二维长度为3的二维1数组
print(x)
x = np.empty((3,3)) #创建一维长度为2，二维长度为3,未初始化的二维数组
print(x)

print('使用arrange生成连续元素')
print(np.arange(6)) # [0,1,2,3,4,5,] 开区间
print(np.arange(0,6,2))  # [0, 2，4]

使用列表生成一维数组
[1 2 3 4 5 6]
int64
使用列表生成二维数组
[[1 2]
 [3 4]
 [5 6]]
2
(3, 2)
使用zero/ones/empty创建数组:根据shape来创建
[ 0.  0.  0.  0.  0.  0.]
[[ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 1.  1.  1.]
 [ 1.  1.  1.]]
[[  6.92827850e-310   1.71278884e-316   6.92826654e-310]
 [  6.92826654e-310   6.92826656e-310   6.92826654e-310]
 [  6.92826654e-310   6.92826654e-310   3.95252517e-322]]
使用arrange生成连续元素
[0 1 2 3 4 5]
[0 2 4]


## 三、指定ndarray数组元素的类型
基本上就是我们常用的类型
看一下例子吧：

In [3]:
import numpy as np

print('生成指定元素类型的数组:设置dtype属性')
x = np.array([1,2.6,3],dtype = np.int64)
print(x) # 元素类型为int64
print(x.dtype)
x = np.array([1,2,3],dtype = np.float64)
print(x) # 元素类型为float64
print(x.dtype)

print('使用astype复制数组，并转换类型')
x = np.array([1,2.6,3],dtype = np.float64)
y = x.astype(np.int32)
print(y) # [1 2 3]
print(x) # [ 1.   2.6  3. ]
z = y.astype(np.float64)
print(z) # [ 1.  2.  3.]

print('将字符串元素转换为数值元素')
x = np.array(['1','2','3'],dtype = np.string_)
y = x.astype(np.int32)
print(x) # ['1' '2' '3']
print(y) # [1 2 3] 若转换失败会抛出异常

print('使用其他数组的数据类型作为参数')
x = np.array([ 1., 2.6,3. ],dtype = np.float32)
y = np.arange(3,dtype=np.int32)
print(y) # [0 1 2]
print(y.astype(x.dtype)) # [ 0.  1.  2.]

生成指定元素类型的数组:设置dtype属性
[1 2 3]
int64
[ 1.  2.  3.]
float64
使用astype复制数组，并转换类型
[1 2 3]
[ 1.   2.6  3. ]
[ 1.  2.  3.]
将字符串元素转换为数值元素
[b'1' b'2' b'3']
[1 2 3]
使用其他数组的数据类型作为参数
[0 1 2]
[ 0.  1.  2.]


## 四、ndarray的矢量化计算
矢量运算：相同大小的数组键间的运算应用在元素上 
矢量和标量运算：“广播”— 将标量“广播”到各个元素

In [4]:
import numpy as np

print('ndarray数组与标量/数组的运算')
x = np.array([1,2,3])
print(x*2) # [2 4 6]
print(x>2) # [False False  True]
y = np.array([3,4,5])
print(x+y) # [4 6 8]
print(x>y) # [False False False]

ndarray数组与标量/数组的运算
[2 4 6]
[False False  True]
[4 6 8]
[False False False]


## 五、ndarray数组的基本索引和切片
一维数组的索引：与Python的列表索引功能相似

多维数组的索引：
* arr[l1:r1,l2:r2]
* arr[1,1]等价于arr\[1\][1]
* [:]代表某个维度的数据

代码实例：

In [5]:
import numpy

print('ndarray的基本索引')
x = numpy.array([[1,2],[3,4],[5,6]])
print(x[0]) # [1,2]
print(x[0][1]) # 2,普通python数组的索引
print(x[0,1])# 同x[0][1]，ndarray数组的索引
x = numpy.array([[[1, 2], [3,4]], [[5, 6], [7,8]]])
print(x[0]) # [[1 2],[3 4]]
y = x[0].copy() # 生成一个副本
z = x[0] # 未生成一个副本
print(y) #  [[1 2],[3 4]]
print(y[0,0]) # 1
y[0,0] = 0
z[0,0] = -1
print(y) # [[0 2],[3 4]]
print(x[0]) # [[-1 2],[3 4]]
print(z) # [[-1 2],[3 4]]

print('ndarray的切片')
x = numpy.array([1,2,3,4,5])
print(x[1:3]) # [2,3] 右边开区间
print(x[:3]) # [1,2,3] 左边默认为 0
print(x[1:]) # [2,3,4,5] 右边默认为元素个数
print(x[0:4:2]) # [1,3] 下标递增2
x = numpy.array([[1,2],[3,4],[5,6]])
print(x[:2]) # [[1 2],[3 4]]
print(x[:2,:1]) # [[1],[3]]
x[:2,:1] = 0 # 用标量赋值
print(x) # [[0,2],[0,4],[5,6]]
x[:2,:1] = [[8],[6]] # 用数组赋值
print(x) # [[8,2],[6,4],[5,6]]

ndarray的基本索引
[1 2]
2
2
[[1 2]
 [3 4]]
[[1 2]
 [3 4]]
1
[[0 2]
 [3 4]]
[[-1  2]
 [ 3  4]]
[[-1  2]
 [ 3  4]]
ndarray的切片
[2 3]
[1 2 3]
[2 3 4 5]
[1 3]
[[1 2]
 [3 4]]
[[1]
 [3]]
[[0 2]
 [0 4]
 [5 6]]
[[8 2]
 [6 4]
 [5 6]]


## 六、ndarray数组的布尔索引和花式索引
布尔索引：使用布尔数组作为索引。arr[condition]，condition为一个条件/多个条件组成的布尔数组。

布尔型索引代码示例：